 /// <reference lib="webworker" />
 import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';
 
 declare let self: ServiceWorkerGlobalScope;
 
 // Clean up old caches from previous versions
 cleanupOutdatedCaches();
 
 // Precache all assets generated by Vite
 precacheAndRoute(self.__WB_MANIFEST);
 
 // Import OneSignal Service Worker SDK
 // This allows OneSignal to handle push events in this unified SW
 importScripts('https://cdn.onesignal.com/sdks/web/v16/OneSignalSDK.sw.js');
 
 // Force the waiting service worker to become the active service worker
 self.addEventListener('install', (event) => {
   console.log('[SW] Installing unified service worker (PWA + OneSignal)');
   self.skipWaiting();
 });
 
 // Take control of all pages immediately
 self.addEventListener('activate', (event) => {
   console.log('[SW] Activating unified service worker');
   event.waitUntil(self.clients.claim());
 });